config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  get 'about', to: 'places#about'
  
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
      resources :users, only: :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

    RATINGS = {
    'One Star'    => '1_star',
    'Two Stars'   => '2_stars',
    'Three Stars' => '3_stars',
    'Four Stars'  => '4_stars',
    'Five Stars'  => '5_stars'
  }

  def humanized_rating
      RATINGS.invert[self.rating]
  end

  def send_comment_email
      NotificationMailer.comment_added(self).deliver
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :place
  belongs_to :user
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :address
  after_validation :geocode

  validates :name, length: { minimum: 3 }
  validates :name, :description, :address, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :places
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!


  def create
      @place = Place.find(params[:place_id])
      @place.comments.create(comment_params.merge(user: current_user))
      redirect_to place_path(@place)

  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
      redirect_to place_path(@place)

  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
   before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @places = Place.all.order("id DESC").paginate(:page => params[:page], :per_page => 7)
  end

  def about
  end

  def edit
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
  end

  def new
    @place = Place.new
  end

  def create
     @place = current_user.places.create(place_params)
     if @place.valid?
        redirect_to root_path
     else
        render :new, status: :unprocessable_entity
     end
  end

  def destroy
      @place = Place.find(params[:id])
      if @place.user != current_user
        return render text: 'Not Allowed', status: :forbidden
       end

      @place.destroy
      redirect_to root_path
  end

  def show
      @place = Place.find(params[:id])
      @comment = Comment.new
      @photo = Photo.new
  end

  def update
      @place = Place.find(params[:id])
      if @place.user != current_user
        return render text: 'Not Allowed', status: :forbidden
      end
      @place.update_attributes(place_params)
      if @place.valid?
        redirect_to root_path
      else
        render :edit, status: :unprocessable_entity
      end
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/ico" href="/assets/favicon.ico">
</head>
<body>



<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to 'Foodster->', root_path, class: 'navbar-brand' %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'About', about_path %>
        </li>
        <li>
            <%= link_to new_place_path do %>
              Add to Foodster
              <i class="glyphicon glyphicon-plus-sign"></i>
              <% end %>
        </li>
        <li><a href="http://elsonmathew.com/" target="_blank">Want More?</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>




<%= yield %>

</body>
</html>

app/views/places/about.html.erb
<div class="booyah-box
col-xs-10 col-xs-offset-1">
  <h1 >What is Foodster?</h1>
  <hr />
  <br />
  <p > Foodster is a multi-cultural, multi-ethnic database full of the world's best eats. Foodster is added to each day by regular people who share their favorite eating spots from around the world! Since 2016, we have additions from ranging from The United States to India! We hope to represent many more countries as Foodster develops. Stay tuned for more updates such as Google Maps integration and User account profiles to make your Foodster experience one of a kind!  Please feel free to add your favorite location by pressing the plus sign below! 
  </p>
  <p>Have questions, comments or concerns? We'd love to hear them! Contact us at: mattcodes.dev@gmail.com</p>
  <i> ~Foodster, Bringing Together a World of Taste!</i>
  <br />
  <br />
  <div><%= link_to new_place_path do %>
  <i class= "glyphicon glyphicon-plus-sign col-xs-10 size_glyph col-xs-offset-5"> </i>
 </div>
 
  <% end %>
  </div>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <div class="new_color">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    </div>
    <%= f.submit 'Update Foodster', class: 'btn btn-primary' %>
    <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div class="carousel-box col-xs-12">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag 'gg.png', class: 'img-responsive' %>
      <div class="carousel-caption">
        Foodster, Bringing Together a World of Taste!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'tt.jpeg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Connect with foodster to log your adventures!
      </div>
    </div>
    <div class="item">
      <%= image_tag 'kk.jpeg', class: 'img-responsive' %>
      <div class="carousel-caption">
        In a new place? Try a new place...
      </div>
    </div>
    <div class="item">
      <%= image_tag 'aa.jpeg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Log in to foodster to see the latest additions!
      </div>
    </div>



  </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>


<% @places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place), :class => 'home_links', :style => 'color: #F7B10C'; %></h1>
    <i><%= place.address %></i><br /><br/>
    <% if place.photos.present? %>

         <%= link_to image_tag(place.photos.first.picture), place_path(place) %>

    <% end %>
    &nbsp
    <p><%= place.description %></p>
     <i><% if place.user.present? %>
      <small><%= place.user.email %></small>
     <% end %></i>
     

    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
            <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
    </div>

<% end %>


<div class= "col-xs-10 col-xs-offset-1" style="text-align: center;">
<%= will_paginate @places, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1 %>
 </div>

app/views/places/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <div class="new_color">
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
   
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i> 
  <p><%= @place.description %></p>
<% @place.photos.each do |photo| %>
  &nbsp<%= image_tag photo.picture %>
  <%= photo.caption %>
<% end %>

&nbsp

<% if @place.latitude.present? && @place.longitude.present? %>

    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCVVhcj7fbiAF8oY6uawF4kzdRla9mWQjc&callback=initMap">
    </script>

    <div id="map"></div>
<% end %>
    <br/>


  <div class="pull-right">
    <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myPhotoModal">Add a photo</button>
    <% if current_user && current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
    <% end %>
    
  </div>
</div>

<!-- Comment Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>



<!-- Photo Modal -->
<div class="modal fade" id="myPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a photo</h4>
      </div>
      <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.file_field :picture %>
        
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Upload", class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </div>
  </div>











</div>



<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1 class="pull-left">Comments</h1>
<!-- Button trigger modal -->
    <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal">Add your thoughts</button>
    
<div class="clear"></div>
<% @place.comments.each do |comment| %>
  <div>
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
          <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <div class="col-xs-8">
    <%= image_tag 'user.png', class: 'small' %>
  </div>
  <br/>

  <div class="col-xs-5">
    <h3><%= @user.email %></h3>
    <br/>
    <h4 class= "user_page_text">Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h5>
    <br/>
    <h5 class="user_page_text"><%= @user.comments.count %> total comments</h4>
    <h5 class="user_page_text"><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h5>
    
  </div>
  <div class="clear"></div>


<br /><br />
<hr />
<h1 class="text-center">My Comments</h1>
<br /><br />
<% @user.comments.each do |comment| %>

  <div class="col-xs-12 col-sm-6">
    <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place), :class => 'home_links', :style => 'color: #F7B10C'; %></h2>

    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>
<br /><br />

<div class="clear"></div>

<div class="clear"></div>
<hr/>
<h1 class="text-center">My Places</h1><br/>
<% @user.places.each do |place| %>
  <div class="col-xs-12 col-sm-6">
    <h1 class=""><%= link_to place.name, place_path(place), :class => 'home_links', :style => 'color: #F7B10C'; %></h1>
    <i><%= place.address %></i><br />
    <p><%= place.description %></p><br />

   

    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
<% end %>